name: Demo API Call

on:
  push:
    branches: [ main ]

jobs:
  demo-call:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use API Key
        env:
          API_KEY: ${{secrets.MY_API_KEY}}
        run: echo "Calling API with key: $API_KEY"
